services:
  web:
    build:
      context: ./biblioshare-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./biblioshare-web:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DEBUG=True

