services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./biblioshare-web:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DEBUG=True
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - ./biblioshare-web:/app
    env_file:
      - ./.env
    environment:
      - DEBUG=True

